### PR TITLE
fix read property fixes #50

### LINKED ISSUE #50: read property not working correctly
In other applications, you must use `doc['property']` to access the property correctly.  otherwise it just reads default values.

### PR DESCRIPTION
**Pull request by seancookr**
needs review @javierg

### CODE REVIEW

File: lib/dolly/document.rb [hunk 1]
```diff
@@ -128,7 +128,8 @@ def write_property name, value
     end
 
     def read_property name
-      self.properties[name].value
+      return self.properties[name].value unless doc[name.to_s]
```
Comment (javierg) [inline lib/dolly/document.rb]: `doc[name.to_s] || self.properties[name].value`

I think this show a flaw in the property object design. Or on how the default value is set into property.

Comment (seancookr) [inline lib/dolly/document.rb]: I would agree.  I guess this helps open up a discussion as to how best to tackle this.  Do you think I should take a look at the property class and see if I hide the logic in there?

Comment (javierg) [inline lib/dolly/document.rb]: > should take a look at the property class and see if I hide the logic in there?

I tried that approach and didn't went well as the instance have not been initialize when the property object is created.

but yeah maybe you can hide the logic in property object where you set a doc through delegation into Property, but this will be set after initialization... of document, that is the hard part

Comment (seancookr) [inline lib/dolly/document.rb]: actually I think this is more a problem with the `Dolly::Document` class, the issue being that I don't want to have to call `doc[some_key]` every time I want to access a property correctly.  I would must rather just call the read method.  I don't think this can be hidden in the property class because the issue is really with the `doc` attribute and how to read the properties from there.

**Comment by seancookr** [comment]
@rubenrails could you perhaps weight in on this?  corresponds to https://github.com/amco/dolly/issues/50

File: lib/dolly/document.rb [hunk 2]
```diff
@@ -53,8 +53,8 @@ def rev= value
     def save
       self.doc['_id'] = self.id if self.id.present?
       self.doc['_id'] = self.class.next_id if self.doc['_id'].blank?
-      set_created_at if respond_to? :set_created_at
-      set_updated_at if respond_to? :set_updated_at
+      set_created_at if respond_to? :created_at
```
Comment (seancookr) [inline lib/dolly/document.rb]: these were not working correctly so I fixed them in here as well as saving a class without the `timestamps!` macro was throwing a no method error.

File: test/document_test.rb [hunk 3]
```diff
@@ -13,6 +13,15 @@ class FooBar < Dolly::Document
...
 class Baz < Dolly::Document; end
 
+class FooBaz < Dolly::Document
+  property :foo, class_name: Hash, default: {}
+
+  def add_to_foo key, value
+    foo[key] ||= value
+    save!
+  end
+end
```
Comment (seancookr) [inline test/document_test.rb]: this method is to test precisely the problem encountered in WS in #50

File: test/document_test.rb [hunk 4]
```diff
@@ -306,6 +315,23 @@ def setup
...
+  end
+
+  test 'can save without timestamps' do
+    resp = {ok: true, id: "foo_bar/1", rev: "FF0000"}
+    FakeWeb.register_uri :put, /http:\/\/localhost:5984\/test\/foo_baz%2F.+/, body: resp.to_json
+    foobaz = FooBaz.new foo: {foo: :bar}
+    assert foobaz.save!
+  end
+
+  test 'property writes work correctly' do
```
Comment (seancookr) [inline test/document_test.rb]: this is to test that method

File: lib/dolly/document.rb (hunk 1 above)
Comment (javierg) [inline lib/dolly/document.rb]: please change the syntax as recomended.

**Comment by rubenrails** [comment]
Looks good to me. @javierg please let me know when the version is bumped, want to test this with some code I have on a different app and see if it breaks my implementation, which I don't think.

:shipit:

**Comment by javierg** [comment]
:shipit:
